name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-qemu
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build 
        run: |
         mkdir bins
         cd ps2classic-ps2classic
         make
         cp *.exe bins/
        
        
      - name: Prepare artifact for packaging
        run: |
           cp /mingw64/bin/*.dll ps2classic-ps2classic/bins/
           
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ${{github.workspace}}/ps2classic-ps2classic/bins
          retention-days: 0
